name: WikiCommand
version: ${project.version}
main: kali.kalikamata.WikiCommand
api-version: 1.13
authors: [Kali]
description: Simple plugin that returns URLs from a config file with static commands and scenarios
website: http://www.grimurrp.com
commands:
  wiki:
    description: Sends player wiki link
  web:
    description: Sends player web link
  map:
    description: Sends player map link
  recipes:
    description: Sends player recipes link
  links:
    description: Sends player link collection